-- supabase/nova.sql — REMPLACÉ, NE PLUS LANCER.
-- Le stockage de Nova (mémoire par profil, quotas par compte) est défini dans le
-- dépôt de l'app : novigo/supabase/migrations/0005_nova_compte.sql
-- (tables nova_memory, nova_usage_account, nova_usage_global + fonctions nova_*).
-- L'ancienne version de ce fichier (nova_fiches / nova_usage, par appareil) n'a
-- jamais été appliquée en production.
